spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
      location: c:\\Project\\React_Source\\sence\\public
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sence?serverTimezone=Asia/Seoul
    username: root
    password: 123456
